# Generated by Django 4.1 on 2022-12-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('CNI', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('filier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filier', verbose_name='filier')),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_classment', models.IntegerField(auto_created=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('etudient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etudiant', verbose_name='Cni etudient')),
                ('filier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filier', verbose_name='filier')),
                ('type_diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typediplome', verbose_name='type de diplome')),
            ],
            options={
                'unique_together': {('etudient', 'filier', 'type_diplome')},
            },
        ),
    ]
