# Generated by Django 4.1 on 2022-12-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filier',
            new_name='Filiere',
        ),
    ]
