# Generated by Django 4.1 on 2022-12-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_filier_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
