# Generated by Django 4.1 on 2022-12-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_filiere_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diplome',
            old_name='filier',
            new_name='filiere',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='filier',
            new_name='filiere',
        ),
        migrations.AlterUniqueTogether(
            name='diplome',
            unique_together={('etudient', 'filiere', 'type_diplome')},
        ),
    ]
