# Generated by Django 4.1 on 2022-12-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_filier_diplome_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplome',
            name='statu',
            field=models.CharField(choices=[(0, 'dossier deposer'), (1, 'dossier encour de traitment'), (3, 'dossier encour de signature'), (4, 'retrait')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filiere', verbose_name='filiere'),
        ),
    ]
