# Generated by Django 4.1 on 2022-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_diplome_statu_alter_diplome_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplome',
            name='statu',
        ),
        migrations.AddField(
            model_name='diplome',
            name='statut',
            field=models.IntegerField(choices=[(0, 'dossier deposer'), (1, 'dossier encour de traitment'), (3, 'dossier encour de signature'), (4, 'retrait')], default=0, max_length=50),
        ),
    ]
