# Generated by Django 4.1 on 2022-12-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_diplome_statu_diplome_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='statut',
            field=models.IntegerField(choices=[(0, 'dossier deposer'), (1, 'dossier encour de traitment'), (3, 'dossier encour de signature'), (4, 'retrait')], default=0),
        ),
    ]
