# Generated by Django 4.1 on 2022-12-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_diplome_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='statut',
            field=models.IntegerField(choices=[(0, 'dossier déposé'), (1, 'dossier en cour de traitement'), (3, 'diplome en cour de signature'), (4, 'diplôme prêt pour retrait')], default=0),
        ),
    ]
