# Generated by Django 4.1 on 2022-12-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_diplome_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='etudient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etudiant', verbose_name='etudient'),
        ),
    ]
