# Generated by Django 4.1 on 2022-12-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_diplome_etudient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='statut',
            field=models.IntegerField(choices=[(0, 'Dossier Déposé'), (1, 'Dossier En Cour De Traitement'), (3, 'Diplome En Cour De Signature'), (4, 'Diplôme Prêt Pour Retrait')], default=0),
        ),
    ]
