# Generated by Django 4.1 on 2023-01-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_diplome_statut'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diplome',
            unique_together={('etudient', 'filiere', 'type_diplome')},
        ),
        migrations.AlterField(
            model_name='diplome',
            name='num_classment',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='diplome',
            unique_together={('num_classment', 'filiere', 'type_diplome'), ('etudient', 'filiere', 'type_diplome')},
        ),
    ]
